Added Android support when running a standalone server
defold/extender pull request #381
Opened 2024-05-16 08:22 UTC by britzl

2024-06-03 09:47 UTC, JCash requested changes

2024-06-03 09:47 UTC, JCash commented on server/docker-base/template.local.properties
> +sdk.dir={{sdk-dir}}
The name of this file is a bit anonymous.
Perhaps add some "gradle" to the name?

2024-06-03 09:47 UTC, JCash commented on server/scripts/rebuild-and-run-standalone-local.sh
> +	export ANDROID_PROGUARD=${ANDROID_ROOT}/proguard.jar
I guess these variables should be in `server/scripts/standalone/service-standalone.sh` ?

2024-06-03 09:47 UTC, JCash commented on server/src/main/java/com/defold/extender/services/GradleService.java
> +        envContext.put("sdk-dir", jobEnvContext.get("env.ANDROID_HOME"));
I'd rather have "android-home" instead?
Better for readability/discoverability imho.

2024-09-16 12:04 UTC, ekharkunov commented
@britzl May be it can be closed in favor of new splited version of Docker images?

2024-10-03 07:35 UTC, britzl commented
-

2024-10-03 07:35 UTC, closed without merging